Repository tehblasian/aita, pull requests merged in 2020-04, with the labels that each got.

#36 Added undersampling to the pipeline
  ml/pipeline.py
Labels: data-processing

#39 Fixed double-save bug in extraction
  data_preparation/extractor.py
Labels: bug

#42 Restructured and updated report
  .gitignore
  README.md
  data_exploration/imgs/class_distribution.png
  data_exploration/imgs/time_analysis.png
  data_exploration/imgs/word_frequency.png
Labels: documentation

#43 [#22] Completed all sections of the report.
  README.md
Labels: documentation

#44 Small readme fix.
  README.md
Labels: documentation
