Repository tehblasian/aita, pull requests merged in 2020-03, with the labels that each got.

#32 [#18, #19, #20, #21] Implemented ML models
  ml/__init__.py
  ml/classifiers.py
  ml/pipeline.py
  pipeline_main.py
Labels: data-training

#31 [#30] Cleaning now removes proper nouns
  cleaner.py
Labels: data-cleaning, task

#29 [#11] [#13] Data Exploration: extract word analytics
  .gitignore
  cleaner.py
  config.py
  constants.py
  data_exploration/class_distribution.py
  data_exploration/time_analysis.py
  data_exploration/word_frequency.py
  data_exploration/word_topics.py
  extractor.py
  requirements.txt
  spark/init_spark.py
Labels: data-exploration, task

#33 Cleaning now makes all words lower-case
  cleaner.py
Labels: data-cleaning

#34 [#14, #15, #16, #17] add transformers
  constants.py
  ml/classifiers.py
  ml/pipeline.py
  ml/transformers.py
  pipeline_main.py
Labels: data-processing, story
